Provide an export option for search results
dag-hammarskjold-library/dlx-rest pull request #1398
Opened 2024-04-15 18:24 UTC by aaronhelton

Closes #779

2024-04-16 22:00 UTC, jbukhari requested changes
#1400

2024-06-04 16:02 UTC, jbukhari reviewed
Changes suggested #1439

2024-06-05 17:45 UTC, jbukhari approved these changes

2024-06-19 19:10 UTC, aaronhelton commented
@jbukhari the CSV download works in the export modal now

2024-06-20 17:17 UTC, jbukhari commented on dlx_rest/api/__init__.py
> +        'of',
Maybe "fields" be more descriptive here?

2024-07-10 00:29 UTC, jbukhari requested changes
#477

2024-07-10 18:02 UTC, jbukhari approved these changes

2024-07-12 15:52 UTC, jbukhari requested changes
#1478

2024-07-12 16:23 UTC, jbukhari requested changes
#1479

2024-08-01 16:53 UTC, jbukhari requested changes
#1501

2024-08-02 19:24 UTC, jbukhari approved these changes

2024-08-06 16:17 UTC, jbukhari requested changes
#1504

2024-08-08 22:47 UTC, jbukhari approved these changes

2024-08-09 12:00 UTC, merged